version: "3"

services:
  clickhouse-server:
    image: yandex/clickhouse-server:19.13
    restart: always
    ports:
      - "9010:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./container-data/clickhouse/data:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  clickhouse-client:
    image: yandex/clickhouse-client:19.13
    depends_on:
      - clickhouse-server
    command: ['--host', 'clickhouse-server']
