version: '3'
services:
  postgres:
    image: postgres:10
    restart: always
    ports:
    - 5432:5432
    environment:
      # POSTGRES_DB=db
      # POSTGRES_USER=admin
      # POSTGRES_PASSWORD=rootroot
    volumes:
    - ./container-data/postgres/data:/var/lib/postgresql/data
